var hunting_parks = [
[ "Chasm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chasm/", undefined ],
[ "Stone Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stone_mt/", new google.maps.LatLng(33.8062166, -84.14575049999996) ],
[ "Lowe Inlet Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lowe_inlet.html", new google.maps.LatLng(53.5553029, -129.5798716) ],
[ "Chilliwack Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chilliwa.html", new google.maps.LatLng(49.1579401, -121.9514666) ],
[ "Jackson Narrows Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/jackson.html", new google.maps.LatLng(52.5248211, -128.30208400000004) ],
[ "Klua Lakes Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/klua_lakes.html", undefined ],
[ "Nimpkish Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nimpkish/", undefined ],
[ "Painted Bluffs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/painted/", undefined ],
[ "Lockhart Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lockhart.html", undefined ],
[ "Green Inlet Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/grninlet.html", new google.maps.LatLng(52.9204576, -128.48312799999997) ],
[ "Denetiah Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/denetiah.html", undefined ],
[ "Pukeashun Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/puke.html", undefined ],
[ "Vargas Island Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/vargas.html", undefined ],
[ "Gilnockie Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gilnocki.html", undefined ],
[ "Sir Alexander Mackenzie Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sir_alex/", new google.maps.LatLng(52.3800945, -127.4709206) ],
[ "South Chilcotin Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/south_chil.html", undefined ],
[ "NenikÃ«kh / Nanika-Kidprice Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nenikekhNanikaKidprice/", undefined ],
[ "Jackson Narrows Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/jackson_narrows/", new google.maps.LatLng(52.5248211, -128.30208400000004) ],
[ "White Lake Grasslands Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wht_lk_grass/", new google.maps.LatLng(49.2952332, -119.59533859999999) ],
[ "Muscovite Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/muscovite_lk.html", undefined ],
[ "Yalakom Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/yalakom/", undefined ],
[ "Windermere Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/winder.html", undefined ],
[ "Marble Range Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/marble_range.html", undefined ],
[ "Granby Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/granby.html", new google.maps.LatLng(45.40322889999999, -72.73406620000003) ],
[ "Mount Pope Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_pope/", undefined ],
[ "Tahsish-Kwois Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tahsish.html", undefined ],
[ "Gold Muchalat Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gold_much.html", undefined ],
[ "Fraser River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fraser_rv/", undefined ],
[ "Eskers Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/eskers/", undefined ],
[ "Cariboo River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cariboo_rv/", undefined ],
[ "Gwyneth Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gwyneth/", undefined ],
[ "Goguka Creek Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/goguka_crk/", undefined ],
[ "Smith River Falls - Fort Halkett Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/smith_halk/", undefined ],
[ "Babine Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/babmtn.html", undefined ],
[ "Beatton River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/beat_riv.html", undefined ],
[ "Mount Blanchet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_blanchet/", undefined ],
[ "Nadina Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nadina/", undefined ],
[ "Lower Raush Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lower_raush/", undefined ],
[ "Skaha Bluffs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/skahaBluffs/", undefined ],
[ "Omineca Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/omineca/", new google.maps.LatLng(55.85244119999999, -124.56299939999997) ],
[ "Fintry Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fintry.html", new google.maps.LatLng(50.1431868, -119.60260340000002) ],
[ "Simson Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/simson.html", undefined ],
[ "Clendinning Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clendinning/", undefined ],
[ "Nechako Canyon Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nech_can.html", undefined ],
[ "South Texada Island Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/s_texada.html", new google.maps.LatLng(49.5187258, -124.17089470000002) ],
[ "Octopus Islands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/octopus.html", undefined ],
[ "Graystokes Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/graystokes/", undefined ],
[ "Taweel Provincial Parks - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/taweel/", undefined ],
[ "Seven Sisters Provincial Park & Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/seven_sis.html", undefined ],
[ "White River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whiteriver.html", undefined ],
[ "Scatter River Old Growth Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/scatter/", new google.maps.LatLng(59.63356499999999, -124.67143709999999) ],
[ "Owyacumish River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/owyacumish/", undefined ],
[ "Mudzenchoot Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mudzenchoot/", undefined ],
[ "Purden Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/purden.html", undefined ],
[ "Castle Rock Hoodoos Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/castle_rock.html", new google.maps.LatLng(39.3722121, -104.85609019999998) ],
[ "Darke Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/darke.html", undefined ],
[ "Muncho Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/muncho_lk/", undefined ],
[ "Seven Sisters Provincial Park & Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/seven_sis/", undefined ],
[ "Ts'yl?os Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ts.html", undefined ],
[ "North Thompson Oxbows East Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nthomp_e.html", new google.maps.LatLng(52.4816647, -119.24175020000001) ],
[ "Inland Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/inlandlk.html", undefined ],
[ "Elk Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/elklakes.html", undefined ],
[ "South Texada Island Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/s_texada/", new google.maps.LatLng(49.5187258, -124.17089470000002) ],
[ "Three Sisters Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/three_sisters_lks/", new google.maps.LatLng(53.5320169, -122.52451840000003) ],
[ "Granby Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/granby/", new google.maps.LatLng(45.40322889999999, -72.73406620000003) ],
[ "Strathcona Provincial Park: Megin/Talbot - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/strathme.html", undefined ],
[ "White Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wht_ridg/", undefined ],
[ "Eagle Bay Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/eagle_bay.html", undefined ],
[ "Mount Richardson Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_richardson/", undefined ],
[ "Churn Creek Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/churn_crk/", undefined ],
[ "Oregon Jack Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/oregon_jack/", new google.maps.LatLng(43.8041334, -120.55420119999997) ],
[ "Lakelse Lake Wetlands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lakelse_lk_wetlands/", new google.maps.LatLng(54.34395, -128.58414400000004) ],
[ "Babine River Corridor Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/babriver.html", new google.maps.LatLng(55.6174061, -127.03712480000002) ],
[ "Stein Valley Nlaka'pamux Heritage Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stein_val/", undefined ],
[ "Elk Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/elk_lk/", undefined ],
[ "Tahsish-Kwois Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tahsish/", undefined ],
[ "Bligh Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bligh_isl.html", new google.maps.LatLng(49.6217056, -126.54289189999997) ],
[ "Uncha Mountain Red Hills Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/uncha_mt/", new google.maps.LatLng(53.9775752, -125.55129970000002) ],
[ "Nimpkish Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nimpkish.html", undefined ],
[ "Roche Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/roche_lk/", undefined ],
[ "Okanagan Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/okanmtn.html", undefined ],
[ "Premier Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/premier/", undefined ],
[ "Bobtail Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bobtail_mtn/", undefined ],
[ "Indian Arm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/indian.html", undefined ],
[ "Swan Creek Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/swan_crk/", undefined ],
[ "Atlin/TÃ©ix'gi Aan Tlein Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/atlin/", undefined ],
[ "Union Passage Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/union_pass.html", new google.maps.LatLng(53.4123959, -129.4285949) ],
[ "Nalbeelah Creek Wetlands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nalbeelah.html", new google.maps.LatLng(54.150917, -128.57443999999998) ],
[ "God's Pocket Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gods_pocket/", undefined ],
[ "Kikomun Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kikomun.html", undefined ],
[ "Gwillim Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gwillim_lk/", undefined ],
[ "North Thompson Oxbows East Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/n_thm_e/", new google.maps.LatLng(52.4816647, -119.24175020000001) ],
[ "Clayoquot Arm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clayoarm.html", undefined ],
[ "Fort George Canyon Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fort_george_cyn/", new google.maps.LatLng(53.68222429999999, -122.7230548) ],
[ "Tranquil Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tranquil.html", undefined ],
[ "Goguka Creek Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/goguka.html", undefined ],
[ "Clayoquot Plateau Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clayoquot_pl/", undefined ],
[ "South Chilcotin Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/south_chilcotin_mts/", undefined ],
[ "Jackman Flats Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/jackman.html", undefined ],
[ "Gibson Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gibson/", undefined ],
[ "Tantalus Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tantalus.html", undefined ],
[ "Coquihalla Summit Recreation Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/coqui_summit.html", undefined ],
[ "Butler Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/butler_ridge/", undefined ],
[ "Clayoquot Plateau Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clayopla.html", undefined ],
[ "Claud Elliott Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/claud_elliott/", undefined ],
[ "Bobtail Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bobtail.html", undefined ],
[ "Slim Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/slim_creek.html", undefined ],
[ "Lower Raush Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/low_raush.html", undefined ],
[ "Stuart Lake Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stuart_lk/", new google.maps.LatLng(54.6093236, -124.6487649) ],
[ "Gibson Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gibson.html", undefined ],
[ "Gilpin Grasslands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gilpin_grasslands.html", undefined ],
[ "Clendinning Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clendinn.html", undefined ],
[ "Francois Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/francois_lk/", undefined ],
[ "Schoolhouse Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/schoolhouse_lk/", undefined ],
[ "Arrowstone Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/arrowsto.html", undefined ],
[ "Pink Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pink_mt/", undefined ],
[ "Heather - Dina Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/heather.html", undefined ],
[ "Chase Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chase.html", undefined ],
[ "Upper Adams River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/up_adams/", new google.maps.LatLng(51.67413639999999, -119.16333629999997) ],
[ "Atna River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/atna_rv/", undefined ],
[ "Catala Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/catala_is/", new google.maps.LatLng(49.838504, -127.0518179) ],
[ "Prophet River Hotsprings Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/prophet_rv_hs/", undefined ],
[ "Babine Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/babine_mtn/", undefined ],
[ "Main Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/main_lk.html", undefined ],
[ "Kalamalka Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kalamalka_lk/", undefined ],
[ "Pine Le Moray Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pine_lemoray/", new google.maps.LatLng(55.4002212, -122.53369370000001) ],
[ "Mount Blanchet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_blanch.html", undefined ],
[ "Anarchist Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/anarchist/", undefined ],
[ "Vaseux Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/vaseux_pa/", undefined ],
[ "Arctic Pacific Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/arctic_pacific_lks/", new google.maps.LatLng(54.3870789, -121.59357649999998) ],
[ "Nuntsi Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nuntsi.html", undefined ],
[ "Upper Lillooet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/upp_lill.html", undefined ],
[ "Bridge River Delta Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bridge_rv/", undefined ],
[ "Eskers Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/eskers.html", undefined ],
[ "Cariboo Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cariboo_mt/", undefined ],
[ "Ed Bird-Estella Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/edbird_estella_lk/", undefined ],
[ "Wapiti Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wapiti_lake.html", undefined ],
[ "Arrowstone Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/arrowstone/", undefined ],
[ "Omineca Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/omineca.html", new google.maps.LatLng(55.85244119999999, -124.56299939999997) ],
[ "Bedard Aspen Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bedard.html", undefined ],
[ "Gladstone (Texas Creek) Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gladston.html", undefined ],
[ "Cornwall Hills Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cornwall.html", undefined ],
[ "Skagit Valley Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/skagit.html", undefined ],
[ "Babine River Corridor Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/babine_rv/", new google.maps.LatLng(55.6174061, -127.03712480000002) ],
[ "Cape Scott Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cape_scott/", undefined ],
[ "Entiako Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/entiako.html", undefined ],
[ "Slim Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/slim_crk/", undefined ],
[ "Lockhart Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lockhart_crk/", undefined ],
[ "Octopus Islands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/octopus/", undefined ],
[ "Valhalla Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/valhalla.html", new google.maps.LatLng(41.0748188, -73.7751326) ],
[ "Chilliwack Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chilliwack_lk/", new google.maps.LatLng(49.1579401, -121.9514666) ],
[ "Sikanni Chief Canyon Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sikan_cy/", new google.maps.LatLng(57.4954821, -122.12595269999997) ],
[ "Cathedral Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cathedral/", new google.maps.LatLng(49.0833333, -120.19999999999999) ],
[ "Netalzul Meadows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/netalzul.html", undefined ],
[ "Bedard Aspen Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bedard_aspen/", undefined ],
[ "Pinecone Burke Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pinecone/", undefined ],
[ "Stuart Lake Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stuart_lk.html", new google.maps.LatLng(54.6093236, -124.6487649) ],
[ "Trembleur Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/trembleur_lk/", undefined ],
[ "Carp Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/carplake.html", undefined ],
[ "Green Inlet Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/green_inlet/", new google.maps.LatLng(52.9204576, -128.48312799999997) ],
[ "Dune Za Keyih Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dune_za/", new google.maps.LatLng(58.4617845, -126.91683610000001) ],
[ "Union Passage Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/union_ps/", new google.maps.LatLng(53.4123959, -129.4285949) ],
[ "Butler Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/butler.html", undefined ],
[ "Tweedsmuir South Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tweeds_s/", undefined ],
[ "Mud Lake Delta Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mud_lk.html", new google.maps.LatLng(52.1201585, -119.16466909999997) ],
[ "Myra-Bellevue Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/myra.html", undefined ],
[ "Evanoff Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/evanoff.html", undefined ],
[ "Fraser River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fraser.html", undefined ],
[ "Tsintsunko Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tsintsun/", undefined ],
[ "Pitman River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pit_riv.html", undefined ],
[ "Nuchatlitz Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nuchatlitz/", undefined ],
[ "Gilnockie Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gilnockie/", undefined ],
[ "Bligh Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bligh_is/", new google.maps.LatLng(49.6217056, -126.54289189999997) ],
[ "Vaseux Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/vaseux_pa.html", undefined ],
[ "Pyramid Creek Falls Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pyramid.html", new google.maps.LatLng(52.355819, -119.16579730000001) ],
[ "Denetiah Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/denetiah/", undefined ],
[ "Hesquiat Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/hesquiat.html", undefined ],
[ "Flores Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/flores.html", undefined ],
[ "Toad River Hot Springs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/toad_rv/", undefined ],
[ "Porcupine Meadows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/porcupine/", undefined ],
[ "Kiskatinaw River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kiskat_riv.html", undefined ],
[ "Horneline Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/horneline.html", undefined ],
[ "Toad River Hot Springs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/toad_rv.html", undefined ],
[ "Thinahtea Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/thinahtea.html", undefined ],
[ "Wapiti Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wapiti_lake/", undefined ],
[ "Pine River Breaks Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pine_riv.html", new google.maps.LatLng(55.69084119999999, -121.35364390000001) ],
[ "Whiskers Point Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whiskers.html", undefined ],
[ "Mount Savona Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_savon.html", undefined ],
[ "Kluskoil Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kluskoil.html", undefined ],
[ "Buse Lake Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/buse_lk/", undefined ],
[ "Upper Seymour River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/upp_sey.html", new google.maps.LatLng(51.6285629, -118.93821230000003) ],
[ "Redfern-Keily Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/redfern/", undefined ],
[ "Stone Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stone.html", new google.maps.LatLng(33.8062166, -84.14575049999996) ],
[ "Hesquiat Peninsula Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/hesquiat_pn/", undefined ],
[ "Schoen Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/schoen_lk/", undefined ],
[ "Thurston Bay Marine - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/thurston/", undefined ],
[ "Dall River Old Growth Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dall_river.html", new google.maps.LatLng(58.65881239999999, -127.70713649999999) ],
[ "Clayoquot Arm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/clayoquot_arm/", undefined ],
[ "Woss Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wosslake/", undefined ],
[ "Tantalus Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tantalus/", undefined ],
[ "Akamina-Kishinena Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/akamina.html", undefined ],
[ "Whiteswan Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whiteswa.html", undefined ],
[ "Bishop River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bishoprv.html", undefined ],
[ "Scatter River Old Growth Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/scatter.html", new google.maps.LatLng(59.63356499999999, -124.67143709999999) ],
[ "Cariboo River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/caribor.html", undefined ],
[ "West Twin Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/west_twin/", undefined ],
[ "Spipiyus Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/spipiyus/", undefined ],
[ "Vargas Island Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/vargas_is/", undefined ],
[ "Old Man Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/oldManLake/", undefined ],
[ "Wire Cache Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wire.html", undefined ],
[ "Dawley Passage Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dawley.html", undefined ],
[ "Callaghan Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/callaghan_lk/", undefined ],
[ "Claud Elliott Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/claud_el.html", undefined ],
[ "Sydney Inlet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sydney/", new google.maps.LatLng(-33.8674869, 151.20699020000006) ],
[ "Sikanni Chief Canyon Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sikan_cy.html", new google.maps.LatLng(57.4954821, -122.12595269999997) ],
[ "Momich Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/momich_lk/", undefined ],
[ "Graham-Laurier Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/graham_laurier/", undefined ],
[ "Penrose Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/penrose.html", new google.maps.LatLng(51.4785165, -127.73793749999999) ],
[ "Finlay-Russel Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/finlay.html", undefined ],
[ "Porcupine Meadows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/porcupin.html", undefined ],
[ "Gwillim Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gwillim.html", undefined ],
[ "Oregon Jack Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/oregonjk.html", new google.maps.LatLng(43.8041334, -120.55420119999997) ],
[ "Simson Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/simson/", undefined ],
[ "Cape Scott Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cape.html", undefined ],
[ "Momich Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/momich.html", undefined ],
[ "Muscovite Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/muscovite_lk/", undefined ],
[ "West Twin Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/west_twin.html", undefined ],
[ "Kianuko Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kianuko.html", undefined ],
[ "North Thompson Islands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/n_thm_is/", undefined ],
[ "Boya Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/boya_lk/", undefined ],
[ "Bugaboo Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bugaboo/", undefined ],
[ "Blue Earth Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/blue_earth_lk/", new google.maps.LatLng(50.5941449, -121.49077729999999) ],
[ "Strathcona Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/planning/mgmtplns/strathcona/", undefined ],
[ "Nalbeelah Creek Wetlands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nalbeelah/", new google.maps.LatLng(54.150917, -128.57443999999998) ],
[ "Sustut Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sustut.html", undefined ],
[ "Mount Richardson Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_richard.html", undefined ],
[ "Mount Savona Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_savona/", undefined ],
[ "Enderby Cliffs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/enderby.html", undefined ],
[ "Kitimat River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kitimat_riv.html", new google.maps.LatLng(54.062911, -128.638353) ],
[ "Upper Lillooet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/up_lillooet/", undefined ],
[ "Sikanni Chief Falls Protected Areas - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sikan_fl/", undefined ],
[ "Harry Lake Aspen Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/harry_lk.html", undefined ],
[ "Foster Arm Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/foster.html", undefined ],
[ "St. Mary's Alpine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stmarys.html", undefined ],
[ "Jesse Falls Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/jesse_falls.html", undefined ],
[ "Sydney Inlet Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sydney.html", undefined ],
[ "Boya Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/boyalake.html", undefined ],
[ "Epper Passage Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/epper.html", undefined ],
[ "Nickel Plate Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nickel_plate/", undefined ],
[ "Bishop River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bishop_rv/", undefined ],
[ "Evanoff Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/evanoff/", undefined ],
[ "Buse Lake Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/buse_lk.html", undefined ],
[ "Bearhole Lake Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bearhole_lk/", new google.maps.LatLng(55.0444666, -120.519541) ],
[ "Taweel Provincial Parks - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/taweel.html", undefined ],
[ "Penrose Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/penrose_is/", new google.maps.LatLng(51.4785165, -127.73793749999999) ],
[ "Marble River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/marbler.html", undefined ],
[ "Pooley Island Conservancy - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pooley_is/", undefined ],
[ "Schoen Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/schoen.html", undefined ],
[ "Bonaparte Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bonapar.html", undefined ],
[ "Pukeashun Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pukeashun/", undefined ],
[ "North Thompson Oxbows Manteau Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nthomp_m.html", new google.maps.LatLng(52.4892107, -119.32158830000003) ],
[ "Strathcona Provincial Park: Megin/Talbot - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/strath_mt/", undefined ],
[ "Codville Lagoon Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/codville.html", new google.maps.LatLng(52.0610327, -127.85276590000001) ],
[ "EC Manning Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/manning.html", undefined ],
[ "Stikine River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stikine/", undefined ],
[ "Upper Raush Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/up_raush/", undefined ],
[ "Elephant Hill Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/elephan.html", undefined ],
[ "Klua Lakes Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/klua_lks/", undefined ],
[ "Blue Earth Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bluerth.html", undefined ],
[ "Kalamalka Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kalamalk.html", undefined ],
[ "Mount Elphinstone Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_elphinstone/", undefined ],
[ "Churn Creek Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/churn.html", undefined ],
[ "Gilpin Grasslands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gilpin_grass/", undefined ],
[ "Dall River Old Growth Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dall_rv/", undefined ],
[ "Flores Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/flores_is/", undefined ],
[ "Stein Valley Nlaka'pamux Heritage Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/steinvly.html", undefined ],
[ "Babine Lake Marine (Pinkut Creek) Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/babine-lk-pinkut-crk/", undefined ],
[ "Codville Lagoon Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/codville_lagoon/", undefined ],
[ "Boulder Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/boulder.html", new google.maps.LatLng(37.12605780000001, -122.12218689999997) ],
[ "White Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whiterid.html", undefined ],
[ "Dahl Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dahl_lk/", undefined ],
[ "Cariboo Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/caribmtn.html", undefined ],
[ "Mud Lake Delta Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mud_lk/", undefined ],
[ "Gitnadoiks River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gitnadoix.html", undefined ],
[ "Epsom Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/epsom.html", undefined ],
[ "Homathko River - Tatlayoko Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/homathko.html", new google.maps.LatLng(51.3883474, -124.68654630000003) ],
[ "Mehatl Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mehatl_crk/", undefined ],
[ "Dawley Passage Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dawley_ps/", undefined ],
[ "Northern Rocky Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/n_rocky/", undefined ],
[ "South Okanagan Grasslands Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/s_ok_grassland/", new google.maps.LatLng(49.0970198, -119.6302273) ],
[ "Sooke Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sooke_mtn/", undefined ],
[ "Quatsino Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/quatsino.html", undefined ],
[ "Enderby Cliffs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/enderby_cliffs/", undefined ],
[ "Height of the Rockies Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/heightof.html", new google.maps.LatLng(50.4970461, -115.21855290000002) ],
[ "Emar Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/emar_lk/", undefined ],
[ "Mount Pope Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_pope.html", undefined ],
[ "Kluskoil Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kluskoil_lk/", undefined ],
[ "Sikanni Chief Falls Protected Areas - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sikan_fl.html", undefined ],
[ "Catala Island Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/catala.html", new google.maps.LatLng(49.838504, -127.0518179) ],
[ "Myra-Bellevue Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/myra/", undefined ],
[ "Nickel Plate Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nickel.html", undefined ],
[ "Ningunsaw Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ningunsaw/", undefined ],
[ "Todagin South Slope Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/todagin.html", new google.maps.LatLng(57.6131701, -129.92173830000002) ],
[ "Stikine River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/stikine.html", undefined ],
[ "Bonaparte Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bonaparte/", undefined ],
[ "Monkman Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/monkman.html", undefined ],
[ "Greenbush Lake Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/grnbush.html", undefined ],
[ "St. Mary's Alpine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/st_marys/", undefined ],
[ "Lakelse Lake Wetlands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lakelse_wetlds.html", undefined ],
[ "Kennedy River Bog Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kennedy_rv_bog/", new google.maps.LatLng(49.10110599999999, -125.6285537) ],
[ "Chasm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chasm.html", undefined ],
[ "Smith River Falls - Fort Halkett Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/smith_halk.html", undefined ],
[ "Spatsizi Plateau Wilderness Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/spatsizi.html", undefined ],
[ "Emar Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/emarlks.html", undefined ],
[ "Graystokes Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/graystokes.html", undefined ],
[ "Six Mile Hill Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/six_mile/", undefined ],
[ "Ed Bird-Estella Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ed_bird.html", undefined ],
[ "Bocock Peak Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bocock_peak/", undefined ],
[ "Brent Mountain Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/brent_mt.html", undefined ],
[ "Main Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/main_lk/", undefined ],
[ "Oliver Cove Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/oliver.html", undefined ],
[ "Snowy Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/snowy/", undefined ],
[ "Epper Passage Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/epper_ps/", undefined ],
[ "Spatsizi Plateau Wilderness Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/spatsizi/", undefined ],
[ "Tweedsmuir South Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tweedsmu.html", undefined ],
[ "High Lakes Basin Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/high_lk.html", undefined ],
[ "Mount Edziza Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mtedziza.html", undefined ],
[ "Painted Bluffs Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/painted.html", undefined ],
[ "Bodega Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bodega_ridge/", undefined ],
[ "Lower Nimpkish Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lower_nim.html", undefined ],
[ "Graham-Laurier Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/graham.html", undefined ],
[ "Northern Rocky Mountains Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/n_rocky.html", undefined ],
[ "Premier Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/premier.html", undefined ],
[ "Chase Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chase/", undefined ],
[ "Bearhole Lake Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bearhole.html", new google.maps.LatLng(55.0444666, -120.519541) ],
[ "Akamina-Kishinena Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/akamina/", undefined ],
[ "Muncho Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/muncho.html", undefined ],
[ "Mount Edziza Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_edziza/", undefined ],
[ "Kakwa Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kakwa.html", undefined ],
[ "Darke Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/darke_lk/", undefined ],
[ "Nechako Canyon Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nechako_canyon/", undefined ],
[ "Uncha Mountain Red Hills Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/uncha.html", new google.maps.LatLng(53.9775752, -125.55129970000002) ],
[ "Three Sisters Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/three_sis.html", undefined ],
[ "Morice Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/moriceLake/", undefined ],
[ "Redfern-Keily Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/redfernk.html", undefined ],
[ "Upper Adams River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/uadams.html", undefined ],
[ "White River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wht_river/", undefined ],
[ "Dahl Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dahl_lake.html", undefined ],
[ "Chukachida River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chuka.html", undefined ],
[ "Epsom Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/epsom/", undefined ],
[ "Pinecone Burke Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pinecone.html", undefined ],
[ "Prophet River Hotsprings Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/proph_hs.html", undefined ],
[ "Top of the World Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/top_world/", undefined ],
[ "Strathcona Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/strath/", undefined ],
[ "Bocock Peak Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bocock.html", undefined ],
[ "Burnie-Shea Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tazdli_wyiez_bin_burnie_shea/", undefined ],
[ "Todagin South Slope Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/todagin/", undefined ],
[ "Wire Cache Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wire_cache/", undefined ],
[ "Fiordland Conservancy - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fiordlan.html", undefined ],
[ "Inland Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/inland_lk/", undefined ],
[ "Holliday Creek Arch Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/holliday.html", undefined ],
[ "Fiordland Conservancy - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fiordland/", undefined ],
[ "Pine River Breaks Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pine_rv/", new google.maps.LatLng(55.69084119999999, -121.35364390000001) ],
[ "Boulder Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/boulder_crk/", undefined ],
[ "Brent Mountain Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/brent_mtn/", undefined ],
[ "Indian Arm Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/indian_arm/", undefined ],
[ "Tatshenshini-Alsek Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tatshen.html", undefined ],
[ "Anarchist Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/anarchist.html", undefined ],
[ "Purden Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/purden_lk/", undefined ],
[ "Gitnadoiks River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gitnadoiks_rv/", undefined ],
[ "Whiskers Point Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whiskers/", undefined ],
[ "Sooke Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sooke_mtn.html", undefined ],
[ "Bodega Ridge Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bodega.html", undefined ],
[ "EC Manning Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ecmanning/", undefined ],
[ "Castle Rock Hoodoos Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/castle_rock/", undefined ],
[ "Syringa Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/syringa/", undefined ],
[ "Sue Channel Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sue_chan/", undefined ],
[ "Thinahtea Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/thinahtea/", undefined ],
[ "Francois Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/francois.html", undefined ],
[ "Skagit Valley Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/skagit/", undefined ],
[ "Kiskatinaw River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kiskatinaw_rv/", undefined ],
[ "Dala-Kildala Rivers Estuaries Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dala_kildala.html", undefined ],
[ "Whiteswan Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/whtswan/", undefined ],
[ "Coquihalla Summit Recreation Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/coquihalla_smt/", undefined ],
[ "Marble River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/marble_rv/", undefined ],
[ "Schoolhouse Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/school.html", undefined ],
[ "Tranquil Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tranquil/", undefined ],
[ "Wrinkly Face Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wrinkly.html", undefined ],
[ "Callaghan Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/callagha.html", undefined ],
[ "Trepanier Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/trepan.html", undefined ],
[ "Giscome Portage Trail Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/giscome/", undefined ],
[ "Atlin/TÃ©ix'gi Aan Tlein Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/atlin.html", undefined ],
[ "Walhachin Oxbows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/walhachi.html", new google.maps.LatLng(50.754262, -120.98994900000002) ],
[ "Mount Elphinstone Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_elphin.html", undefined ],
[ "Lowe Inlet Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lowe_inlet/", undefined ],
[ "Finlay-Russel Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/finlay_russel/", new google.maps.LatLng(57.4458324, -126.00222530000002) ],
[ "Mount Assiniboine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mtassini.html", undefined ],
[ "Rubyrock Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ruby.html", undefined ],
[ "Carmanah Walbran Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/carmanah.html", undefined ],
[ "Finger-Tatuk Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/finger.html", undefined ],
[ "Strathcona Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/strathco.html", undefined ],
[ "Kitsumkalum Lake North Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kitsum_north.html", undefined ],
[ "Peace River Corridor Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/peace_rv/", undefined ],
[ "Big Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bigcreek.html", undefined ],
[ "Nuchatlitz Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nuchatli.html", undefined ],
[ "Ts'yl?os Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tsilos/", undefined ],
[ "Pink Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pink_mt.html", undefined ],
[ "Nahatlatch Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nahatlatch/", new google.maps.LatLng(49.97832709999999, -121.78603720000001) ],
[ "Sir Alexander Mackenzie Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/alex_mack.html", undefined ],
[ "Eagle Bay Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/eagle_bay/", undefined ],
[ "Owyacumish River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/owyacumish.html", undefined ],
[ "Dala-Kildala Rivers Estuaries Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dala_kildala_rv/", undefined ],
[ "Finger-Tatuk Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/finger/", undefined ],
[ "Silver Star Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/silver_star/", undefined ],
[ "Gladstone (Texas Creek) Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gladstone/", undefined ],
[ "Netalzul Meadows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/netalzul/", undefined ],
[ "Kikomun Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kikomun_crk/", undefined ],
[ "Tsintsunko Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tsintsun.html", undefined ],
[ "White Lake Grasslands Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/white_lk.html", undefined ],
[ "Windermere Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/windermere_lake/", undefined ],
[ "Tatshenshini-Alsek Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tatshens/", undefined ],
[ "Upper Raush Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/upp_raush.html", undefined ],
[ "Marble Range Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/marble_ran/", undefined ],
[ "Fintry Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fintry/", undefined ],
[ "Nuntsi Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nuntsi/", undefined ],
[ "Fort George Canyon Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fort_george.html", new google.maps.LatLng(53.68222429999999, -122.7230548) ],
[ "Tatlatui Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tatlatui.html", undefined ],
[ "Foster Arm Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/foster_arm/", undefined ],
[ "Itcha Ilgachuz Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/itcha_ilgachuz/", undefined ],
[ "Dune Za Keyih Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/dune_za.html", undefined ],
[ "Mehatl Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mehatl.html", undefined ],
[ "Walhachin Oxbows Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/walhachn/", new google.maps.LatLng(50.754262, -120.98994900000002) ],
[ "Roche Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/rochlk.html", undefined ],
[ "Wrinkly Face Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wrinkly/", undefined ],
[ "Mudzenchoot Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mudzen.html", undefined ],
[ "Trembleur Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tremb.html", undefined ],
[ "God's Pocket Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gods_pock.html", undefined ],
[ "Woss Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wosslake.html", undefined ],
[ "Carmanah Walbran Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/carmanah/", undefined ],
[ "Ningunsaw Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/ningun.html", undefined ],
[ "Upper Seymour River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/up_seymour/", undefined ],
[ "Thurston Bay Marine - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/thurston.html", undefined ],
[ "Big Creek Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/big_crk/", undefined ],
[ "Carp Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/carp_lk/", undefined ],
[ "Silver Star Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/silver_star.html", undefined ],
[ "Monkman Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/monkman/", undefined ],
[ "Quatsino Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/quatsino/", undefined ],
[ "Beatton River Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/beatton_rv/", undefined ],
[ "South Okanagan Grasslands Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/s_okan.html", undefined ],
[ "Entiako Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/entiako/", undefined ],
[ "Cathedral Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cathedra.html", new google.maps.LatLng(49.0833333, -120.19999999999999) ],
[ "Trepanier Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/trepanier/", undefined ],
[ "Mount Assiniboine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/mt_assiniboine/", undefined ],
[ "Cornwall Hills Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/cornwall_hills/", undefined ],
[ "Greenbush Lake Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/greenbush_lk/", undefined ],
[ "Sustut Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/sustut/", undefined ],
[ "Okanagan Mountain Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/okana_mt/", undefined ],
[ "Pine Le Moray Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pn_lemoray.html", undefined ],
[ "Oliver Cove Marine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/oliver/", new google.maps.LatLng(52.3113843, -128.35494219999998) ],
[ "Fred Antoine Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/fred_antoine/", undefined ],
[ "North Thompson Islands Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nthompis.html", undefined ],
[ "Chukachida River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/chukachida_rv/", undefined ],
[ "Junction Sheep Range Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/junction/", new google.maps.LatLng(51.7837587, -122.4338166) ],
[ "Pitman River Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pitman_rv/", undefined ],
[ "Top of the World Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/topofthe.html", undefined ],
[ "Giscome Portage Trail Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/giscome.html", undefined ],
[ "Pyramid Creek Falls Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/pyramid/", new google.maps.LatLng(52.355819, -119.16579730000001) ],
[ "Itcha Ilgachuz Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/itcha.html", undefined ],
[ "Wells Gray Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/wells_gry/", undefined ],
[ "Bugaboo Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/bugaboo.html", undefined ],
[ "Syringa Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/syringa.html", undefined ],
[ "Gold Muchalat Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/gold_muchalat/", undefined ],
[ "Junction Sheep Range Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/junction.html", undefined ],
[ "Arctic Pacific Lakes Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/arctic.html", undefined ],
[ "Tatlatui Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/tatlatui/", undefined ],
[ "Lower Nimpkish Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/lower_nimpkish/", undefined ],
[ "Kennedy River Bog Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/kennedy.html", undefined ],
[ "Peace River Corridor Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/peace_riv.html", undefined ],
[ "Hesquiat Peninsula Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/hesqpen.html", undefined ],
[ "Rubyrock Lake Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/rubyrock_lk/", undefined ],
[ "Valhalla Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/valhalla/", undefined ],
[ "Spipiyus Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/spipiyus.html", undefined ],
[ "Nahatlatch Provincial Park and Protected Area - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/nahat.html", undefined ],
[ "North Thompson Oxbows Manteau Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/n_thm_mn/", new google.maps.LatLng(52.4892107, -119.32158830000003) ],
[ "Hai Lake - Mount Herman Provincial Park - BC Parks", "http://www.env.gov.bc.ca/bcparks/explore/parkpgs/hai_mt_herm.html", undefined ],
];
